// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM9nztMHom4yfl91q-CxSLksr0xUgJuL8',
    appId: '1:513788178083:web:451812faafa412eec25916',
    messagingSenderId: '513788178083',
    projectId: 'smart-safety-app-52dec',
    authDomain: 'smart-safety-app-52dec.firebaseapp.com',
    storageBucket: 'smart-safety-app-52dec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJhhyYKJFz356toFabAQvsFGsrPmhWHQ',
    appId: '1:513788178083:android:8aa501ac997e7894c25916',
    messagingSenderId: '513788178083',
    projectId: 'smart-safety-app-52dec',
    storageBucket: 'smart-safety-app-52dec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCsPGS1LHBqQjNES0Sgbs52Hyak6r9Z4',
    appId: '1:513788178083:ios:18b94dfedf8540ffc25916',
    messagingSenderId: '513788178083',
    projectId: 'smart-safety-app-52dec',
    storageBucket: 'smart-safety-app-52dec.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyCsPGS1LHBqQjNES0Sgbs52Hyak6r9Z4',
    appId: '1:513788178083:ios:18b94dfedf8540ffc25916',
    messagingSenderId: '513788178083',
    projectId: 'smart-safety-app-52dec',
    storageBucket: 'smart-safety-app-52dec.firebasestorage.app',
    iosBundleId: 'com.example.smartSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM9nztMHom4yfl91q-CxSLksr0xUgJuL8',
    appId: '1:513788178083:web:3365313c8d831cbdc25916',
    messagingSenderId: '513788178083',
    projectId: 'smart-safety-app-52dec',
    authDomain: 'smart-safety-app-52dec.firebaseapp.com',
    storageBucket: 'smart-safety-app-52dec.firebasestorage.app',
  );
}
